# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-02 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('男', 'man'), ('女', 'women')], max_length=10)),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('receiver', models.CharField(max_length=64)),
            ],
        ),
    ]
