# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
