# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(default='', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=16)),
                ('img_url', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AllClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Binfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateTimeField(auto_now_add=True)),
                ('item_no', models.CharField(default='', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64, null=True, unique=True)),
                ('cComment', models.CharField(default='', max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('who_send', models.CharField(choices=[('1', '商家'), ('0', '用户')], default=0, max_length=10)),
                ('sign', models.CharField(choices=[('1', '已读'), ('0', '未读')], default=0, max_length=10)),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Binfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_number', models.CharField(db_index=True, default='', max_length=16, unique=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('img_url', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('count', models.IntegerField(default='')),
                ('see_nums', models.IntegerField(default='0')),
                ('pay_nums', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=64, null=True, unique=True)),
                ('dComment', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='')),
                ('trade_no', models.CharField(max_length=16, null=True)),
                ('success', models.CharField(choices=[('1', '已支付'), ('0', '未支付')], default=0, max_length=10)),
                ('c_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.CreateModel(
            name='SecKill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(default='', max_length=64, null=True)),
                ('tPrice', models.IntegerField(default='', null=True)),
                ('tDescribe', models.CharField(default='', max_length=128, null=True)),
                ('tDate', models.DateTimeField(default='', null=True)),
                ('tCount', models.IntegerField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=16, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('男', 'man'), ('女', 'women')], max_length=10)),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(default='', max_length=32)),
                ('email', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=11)),
                ('receiver', models.CharField(default='', max_length=64)),
                ('code', models.CharField(default='', max_length=6)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='VCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see_num', models.IntegerField(default='0')),
                ('pay_num', models.IntegerField(default='0')),
                ('classlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.UserInfo'),
        ),
        migrations.AddField(
            model_name='pay',
            name='p_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo', to_field='name'),
        ),
        migrations.AddField(
            model_name='mcomment',
            name='uname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo', to_field='name'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment', to_field='content'),
        ),
        migrations.AddField(
            model_name='chat',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo'),
        ),
        migrations.AddField(
            model_name='car',
            name='class_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo', to_field='name'),
        ),
        migrations.AddField(
            model_name='border',
            name='logistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Logistics'),
        ),
        migrations.AddField(
            model_name='border',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Pay'),
        ),
        migrations.AddField(
            model_name='allclass',
            name='classlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='ad',
            name='classlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='acomment',
            name='cname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.CComment', to_field='cname'),
        ),
        migrations.AddField(
            model_name='acomment',
            name='uname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.MComment'),
        ),
    ]
