# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='addr',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='receiver',
            field=models.CharField(default='', max_length=64),
        ),
    ]
