# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(default='', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=16)),
                ('img_url', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AllClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_number', models.CharField(db_index=True, default='', max_length=16, unique=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('img_url', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('count', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='')),
                ('success', models.CharField(choices=[('1', '已支付'), ('0', '未支付')], default=0, max_length=10)),
                ('c_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=16, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('男', 'man'), ('女', 'women')], max_length=10)),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(default='', max_length=32)),
                ('email', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=11)),
                ('receiver', models.CharField(default='', max_length=64)),
                ('code', models.CharField(default='', max_length=6)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='pay',
            name='p_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo', to_field='name'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment', to_field='content'),
        ),
        migrations.AddField(
            model_name='car',
            name='class_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo', to_field='name'),
        ),
        migrations.AddField(
            model_name='allclass',
            name='classlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='ad',
            name='classlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
    ]
