# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190307_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
