# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190305_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('l_number', models.CharField(db_index=True, default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
                ('color', models.CharField(default='', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('count', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_number', models.CharField(db_index=True, default='', max_length=16, unique=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('color', models.CharField(default='', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('count', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('l_number', models.CharField(db_index=True, default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
                ('color', models.CharField(default='', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('count', models.IntegerField(default='')),
                ('success', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='classlist',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment', to_field='content', unique=True),
        ),
        migrations.AddField(
            model_name='allclass',
            name='classlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Car'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment', to_field='content'),
        ),
    ]
