# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190326_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see_num', models.IntegerField(default='0')),
                ('pay_num', models.IntegerField(default='0')),
                ('classlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.AddField(
            model_name='border',
            name='logistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Logistics'),
        ),
        migrations.AddField(
            model_name='border',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Pay'),
        ),
    ]
