# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20190329_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='pay_nums',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='see_nums',
            field=models.IntegerField(default='0'),
        ),
    ]
