# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20190307_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
