# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_classlist_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(default='', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=16)),
                ('img_url', models.CharField(default='', max_length=300)),
                ('classlist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
