# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20190329_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='bdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='border',
            name='item_no',
            field=models.CharField(default='', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='trade_no',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
