# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20190310_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
