# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-31 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20190329_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sign', models.CharField(choices=[('1', '已读'), ('0', '未读')], default=0, max_length=10)),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Binfo')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo')),
            ],
        ),
    ]
