# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-17 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20190310_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='car',
            name='l_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='car',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='comment',
        ),
        migrations.AddField(
            model_name='car',
            name='class_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.ClassList', to_field='l_number'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo', to_field='name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
