# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-17 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20190317_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Comment'),
        ),
    ]
