# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20190404_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
