# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-04 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_auto_20190404_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcomment',
            name='cid',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
