# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_mcomment_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(default='', max_length=64, null=True)),
                ('tPrice', models.IntegerField(default='', max_length=16, null=True)),
                ('tDescribe', models.CharField(default='', max_length=128, null=True)),
                ('tDate', models.DateTimeField(default='', null=True)),
                ('tCount', models.IntegerField(default='', null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo')),
            ],
        ),
    ]
