# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tPrice',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.UserInfo'),
        ),
    ]
