# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-31 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binfo',
        ),
    ]
